#ifndef ERASEFILEPLUGIN_GLOBAL_H
#define ERASEFILEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ERASEFILEPLUGIN_LIB
# define ERASEFILEPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define ERASEFILEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // ERASEFILEPLUGIN_GLOBAL_H
