#ifndef TRASHCLEANPLUGIN_GLOBAL_H
#define TRASHCLEANPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef TRASHCLEANPLUGIN_LIB
# define TRASHCLEANPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define TRASHCLEANPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TRASHCLEANPLUGIN_GLOBAL_H
